//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int Id { get; set; }
        public double Quantity { get; set; }
        public string Measure { get; set; }
        public string Name { get; set; }
        public Nullable<int> Recepie_Id { get; set; }
    
        public virtual Recepie Recepy { get; set; }
    }
}
