//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecepieInfo
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public int Rating { get; set; }
        public Nullable<int> CreatedBy_Id { get; set; }
        public Nullable<int> Recepie_Id { get; set; }
    
        public virtual Recepie Recepie { get; set; }
        public virtual User User { get; set; }
    }
}
