//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recepie()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.RecepieInfoes = new HashSet<RecepieInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public int Difficulty { get; set; }
        public int Duration { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> CreatedBy_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecepieInfo> RecepieInfoes { get; set; }
        public virtual User User { get; set; }
    }
}
